export const EnvKey = {
  MODE: 'MODE',
  PORT: 'PORT',
  IS_SECURE: 'IS_SECURE',
  DB_CONNECTION_URI: 'DB_CONNECTION_URI',
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_REFRESH_KEY: 'JWT_REFRESH_KEY',
  JWT_LIMIT: 'JWT_LIMIT',
  API_KEY: 'API_KEY',
  SECRET_KEY: 'SECRET_KEY',
  THROTTLE_TTL: 'THROTTLE_TTL',
  THROTTLE_LIMIT: 'THROTTLE_LIMIT',
};
